# Generated by Django 6.0.6 on 2026-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('public_key', models.TextField()),
                ('market', models.CharField(default='LSO', max_length=10)),
                ('environment', models.CharField(default='sandbox', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('b2b', 'B2B Single Payment'), ('b2c', 'B2C Single Payment'), ('c2b', 'C2B Single Payment'), ('reversal', 'Reversal'), ('tx_status', 'TX Status Query'), ('direct_debit', 'Direct Debit Create'), ('session', 'Get Session')], max_length=20)),
                ('request_payload', models.TextField(blank=True)),
                ('response_payload', models.TextField(blank=True)),
                ('response_code', models.CharField(blank=True, max_length=20)),
                ('status_code', models.IntegerField(default=0)),
                ('endpoint_url', models.CharField(blank=True, max_length=300)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
